/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author alanm
 */
public class Viajes extends javax.swing.JFrame {

    /**
     * Creates new form Viajes
     */
    public Viajes() {
        initComponents();
        this.setLocationRelativeTo(null);
        backArrow();
        icono();
    }
    private void icono(){
        setIconImage(new ImageIcon(getClass().getResource("../Assets/logo3.png")).getImage());
    }
private void backArrow(){
    try {
        ImageIcon arrow;
        arrow = new ImageIcon(getClass().getResource("/Assets/back_arrow.png"));
        Icon arrowIcon = new ImageIcon(arrow.getImage().getScaledInstance(lbl_back.getWidth(),
                lbl_back.getHeight(), Image.SCALE_SMOOTH));
        lbl_back.setIcon(arrowIcon);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado al cargar los recursos");
        System.out.println("error");
    }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_rergesar = new javax.swing.JLabel();
        lbl_destino = new javax.swing.JLabel();
        lbl_fecha1 = new javax.swing.JLabel();
        lbl_asientos = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_destino2 = new javax.swing.JLabel();
        lbl_fecha2 = new javax.swing.JLabel();
        comboDestinoSearch = new rojerusan.RSComboMetro();
        dateSearch = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableViajes = new rojerusan.RSTableMetro();
        comboDestino = new rojerusan.RSComboMetro();
        comboAsientos = new rojerusan.RSComboMetro();
        dateFecha = new rojerusan.RSDateChooser();
        btnEliminar = new javax.swing.JButton();
        lbl_asientos1 = new javax.swing.JLabel();
        txtObservaciones = new rojerusan.RSMetroTextFullPlaceHolder();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de Viajes");
        setIconImages(null);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_rergesar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_rergesar.setText("Regresar");
        jPanel2.add(lbl_rergesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 20));

        lbl_destino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_destino.setText("Destino");
        jPanel2.add(lbl_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lbl_fecha1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fecha1.setText("Fecha");
        jPanel2.add(lbl_fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lbl_asientos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_asientos.setText("Observaciones");
        jPanel2.add(lbl_asientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));

        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 40));

        btnCrear.setBackground(new java.awt.Color(5, 101, 249));
        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear viaje");
        btnCrear.setBorder(null);
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 100, 30));

        btnModificar.setBackground(new java.awt.Color(0, 102, 255));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 100, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_destino2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_destino2.setText("Destino");
        jPanel3.add(lbl_destino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lbl_fecha2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_fecha2.setText("Fecha");
        jPanel3.add(lbl_fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel3.add(comboDestinoSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 400, -1));

        dateSearch.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateSearchPropertyChange(evt);
            }
        });
        jPanel3.add(dateSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 400, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 130));

        jScrollPane2.setViewportView(tableViajes);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 490, 360));
        jPanel2.add(comboDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        jPanel2.add(comboAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));
        jPanel2.add(dateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 200, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 100, 30));

        lbl_asientos1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_asientos1.setText("Asientos");
        jPanel2.add(lbl_asientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));
        jPanel2.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 200, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_lbl_backMouseClicked

    private void dateSearchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateSearchPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dateSearchPropertyChange

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrear;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModificar;
    public rojerusan.RSComboMetro comboAsientos;
    public rojerusan.RSComboMetro comboDestino;
    public rojerusan.RSComboMetro comboDestinoSearch;
    public rojerusan.RSDateChooser dateFecha;
    public com.toedter.calendar.JDateChooser dateSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_asientos;
    private javax.swing.JLabel lbl_asientos1;
    public javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_destino;
    private javax.swing.JLabel lbl_destino2;
    private javax.swing.JLabel lbl_fecha1;
    private javax.swing.JLabel lbl_fecha2;
    private javax.swing.JLabel lbl_rergesar;
    public rojerusan.RSTableMetro tableViajes;
    public rojerusan.RSMetroTextFullPlaceHolder txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
